# ==============================================================================
# STAGE 1: DEPS (Dependencies)
# Why: We separate dependency installation into its own stage. This allows Docker
# to cache the downloaded node_modules. If our package.json hasn't changed,
# Docker skips this step in future builds, making deployments much faster.
# ==============================================================================
# We use alpine (a super lightweight Linux distribution) to keep the image small.
FROM node:20-alpine AS deps

# libc6-compat is often required by Node.js native addons (like process monitoring)
# under Alpine Linux. It ensures compatibility with standard C libraries.
RUN apk add --no-cache libc6-compat

# Set the working directory inside the container to /app
WORKDIR /app

# Copy ONLY the package manager files first. We don't copy the whole codebase yet.
# By doing this, the 'npm ci' step is only re-run if these specific files change.
COPY package.json package-lock.json .npmrc* ./

# Run 'npm ci' (clean install with legacy-peer-deps for React 19 compatibility).
RUN npm ci --legacy-peer-deps

# ==============================================================================
# STAGE 2: BUILDER (Compiling the Next.js app)
# Why: We need a stage to compile our TypeScript and React code into vanilla JS.
# We don't want to run the final app from this stage because it contains
# development tools, source code, and massive node_modules that bloat the image.
# ==============================================================================
FROM node:20-alpine AS builder
WORKDIR /app

# Copy the node_modules we just installed in the 'deps' stage into this stage.
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of our application source code into the container.
COPY . .

# IMPORTANT: Disable Next.js telemetry (data collection) to speed up the build
# and ensure privacy in our production environment.
ENV NEXT_TELEMETRY_DISABLED=1

# Run the Next.js build process. Because we set 'output: "standalone"' in 
# next.config.mjs, Next.js will automatically trace our imports and create a 
# minimal, self-contained folder containing ONLY the files needed to run.
RUN npm run build

# ==============================================================================
# STAGE 3: RUNNER (The Final Production Image)
# Why: This is the actual image that gets pushed to our server. We only copy
# the compiled standalone files from the 'builder' stage. This reduces our 
# image size from ~1GB+ down to ~150MB, saving money and improving startup time.
# ==============================================================================
FROM node:20-alpine AS runner
WORKDIR /app

# Set the environment to production to ensure React and Next.js run in highly
# optimized modes (disabling dev warnings and enabling caching).
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Security Best Practice: Never run applications as the 'root' user!
# We create a new user group 'nodejs' and a new user 'nextjs'.
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the static assets (images, fonts, etc.) from the builder.
# Next.js serves these directly from the /public folder.
COPY --from=builder /app/public ./public

# Copy the automatically generated Next.js standalone folder.
# We set ownership (--chown) to our non-root 'nextjs' user for security.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy the static chunks generated during the build process.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Tell Docker that we want to switch from the 'root' user to our 'nextjs' user.
# Any commands run after this point are restricted by this user's permissions.
USER nextjs

# Expose port 3000 to tell Docker which port the app will be listening on.
EXPOSE 3000

# Set the PORT environment variable which Next.js will read when starting up.
ENV PORT=3000

# Start the application using the minimal server.js file generated by the 
# standalone output mode. This skips the heavy 'next start' command.
CMD ["node", "server.js"]
