/**
 * TypeScript types for AI Roadmap Generation feature
 * 
 * These types define the structure of roadmaps, tasks, and related data
 * used throughout the application for type safety.
 */

// =====================================================
// Database Types (match Supabase schema)
// =====================================================

/**
 * Roadmap record from database
 * Represents a user's AI-generated learning roadmap
 */
export interface RoadmapRecord {
    id: string
    user_id: string
    generation_mode: 'quick' | 'advanced'
    duration_days: number
    form_responses: RoadmapFormResponses
    assessment_data: AssessmentDataSummary[]
    weak_areas: string[]
    strong_areas: string[]
    roadmap_content: RoadmapContent
    is_active: boolean
    generated_at: string
    expires_at: string
    created_at: string
    updated_at: string
}

/**
 * Progress record for tracking task completion
 */
export interface RoadmapProgressRecord {
    id: string
    roadmap_id: string
    user_id: string
    week_number: number | null
    day_number: number
    task_id: string
    completed: boolean
    completed_at: string | null
    created_at: string
    updated_at: string
}

/**
 * Generation limit record for monthly tracking
 */
export interface RoadmapGenerationLimit {
    id: string
    user_id: string
    month_year: string // Format: "2024-12"
    generation_count: number
    last_generated_at: string | null
    created_at: string
    updated_at: string
}

// =====================================================
// Form Input Types
// =====================================================

/**
 * User's form responses used to generate the roadmap
 */
export interface RoadmapFormResponses {
    mode: 'quick' | 'advanced'
    durationDays: number
    learningGoal: string
    skillLevel: 'beginner' | 'intermediate' | 'advanced'
    hoursPerDay: number
    daysPerWeek: number
    // Advanced mode only
    learningPace?: 'fast' | 'moderate' | 'relaxed'
    learningStyles?: ('video' | 'reading' | 'hands-on')[]
    specificTopics?: string[]
    careerGoal?: 'job_ready' | 'freelancing' | 'hobby' | 'promotion'
    priorExperience?: string
    budgetPreference?: 'free_only' | 'budget_friendly' | 'no_limit'
}

/**
 * Summary of user's assessment data used for roadmap generation
 */
export interface AssessmentDataSummary {
    id: string
    certification_level: string
    final_score: number
    completed_at: string
}

// =====================================================
// Gemini API Types
// =====================================================

/**
 * Input for Gemini roadmap generation
 */
export interface RoadmapGenerationInput {
    durationDays: number
    userGoals: string
    learningPace: 'fast' | 'moderate' | 'relaxed'
    hoursPerDay: number
    daysPerWeek: number
    weakAreas: string[]
    strongAreas: string[]
    assessmentScores: {
        level: string
        score: number
    }[]
    preferredLearningStyle: ('video' | 'reading' | 'hands-on')[]
    currentSkillLevel: 'beginner' | 'intermediate' | 'advanced'
    specificTopics?: string[]
}

// =====================================================
// Roadmap Content Types (Gemini output structure)
// =====================================================

/**
 * Complete roadmap structure generated by Gemini
 */
export interface RoadmapContent {
    weeks: RoadmapWeek[]
    projects: RoadmapProject[]
    resources: RoadmapResource[]
    tips: string[]
}

/**
 * A single week in the roadmap
 */
export interface RoadmapWeek {
    weekNumber: number
    goal: string
    days: RoadmapDay[]
}

/**
 * A single day in a week
 */
export interface RoadmapDay {
    dayNumber: number
    focus: string
    isRestDay?: boolean
    tasks: RoadmapTask[]
}

/**
 * A single task to complete
 */
export interface RoadmapTask {
    id: string // Format: "d1_t1" (day 1, task 1)
    title: string
    description: string
    estimatedMinutes: number
    type: 'learn' | 'practice' | 'project' | 'review'
}

/**
 * A suggested project in the roadmap
 */
export interface RoadmapProject {
    title: string
    description: string
    weekToStart: number
    difficulty: 'beginner' | 'intermediate' | 'advanced'
    estimatedHours: number
    learningObjectives: string[]
}

/**
 * A learning resource (article, video, etc.)
 */
export interface RoadmapResource {
    title: string
    url: string
    type: 'article' | 'video' | 'documentation' | 'course' | 'book'
    relevantWeeks: number[]
    isFree?: boolean
}

// =====================================================
// UI/Component Types
// =====================================================

/**
 * Generation limit check result
 */
export interface GenerationLimitStatus {
    canGenerate: boolean
    used: number
    remaining: number
    resetsOn: Date
}

/**
 * Assessment requirement check result
 */
export interface AssessmentRequirementStatus {
    hasEnoughAssessments: boolean
    completedCount: number
    minimumRequired: number
    recommendedCount: number
}

/**
 * Progress statistics for roadmap view
 */
export interface RoadmapProgressStats {
    totalTasks: number
    completedTasks: number
    percentComplete: number
    daysRemaining: number
    isExpired: boolean
    currentWeek: number
    currentDay: number
}

/**
 * View mode options for roadmap display
 */
export type RoadmapViewMode = 'list' | 'calendar' | 'kanban'

/**
 * Time filter options
 */
export type RoadmapTimeFilter = 'week' | 'month' | 'all'
